### PR TITLE
Two new script added for handling header repetition

### PR DESCRIPTION
**Pull request by dpauld**
The 9_combine_column_v1_singleDistrict handles each district folder individually. The other one handles all of them at the same time and saves them into a new directory in the root. Since people are working in the cleanedCSVs directory, I did not want to mess up things, that's why saved them in a new folder in the root directoy.

### CODE REVIEW

**Comment by yasserius** [comment]
Hey, looks awesome, but you created a copy of the cleaned_CSVs folder and combined the headers in that? Creating two copies of the data will be confusing, so we only can keep one. If you are confident that the headers are merged and all data is good, then please just keep one folder with the name "cleaned_CSVs".

Also, can you please tell me how you detected multi line headers?

**Comment by dpauld** [comment]
Exactly, The script creates a copy of the cleaned_CSVs folder with a different name and combined the headers in that. I have initialized the first header row as the target row. And then just used a loop to go through each header element of the next row and checked whether the header of the target row matches the next row, if they don't match then I merged them into the first header row. The loop breaks when the next row becomes a data row.

**Comment by dpauld** [comment]
If creating a copy of cleaned_CSVs creates confusion then I can create a new folder inside each district folder of the cleaned_CSVs. Each new folder will contain all CSVs with the merged header of that district.

**Comment by yasserius** [comment]
Is it possible to manually check every merged header? I would feel safer then. Can you please edit the script and print out the paths of the files that got merged? I want to check them out manually. A txt file containing the file paths will be great.

I am sorry for the inconvenience but have to make the process proper.

**Pull request closed without merging**
